name: kicad-bot

on:
  push:
    branches: [main]
    paths: ["**.kicad_sch", "**.kicad_pcb"]
  pull_request:
    paths: ["**.kicad_sch", "**.kicad_pcb"]

jobs:
  kicad-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: embedded-pro/kicad-bot@dec919920aede0a8f8bc3cbb5252157b800a92a3 # v0.1.2
        with:
          run-verify: "true"
          run-diff: "true"
          run-fab: "true"
          fail-on-erc: "true"
          fail-on-drc: "true"
